---
on:
  schedule:
    - cron: '39 2 * * *'
  workflow_dispatch:

name: Generate Emojis
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check for Updates
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Check for new releases
        id: release-check
        run: |
          cd unicode-emoji-json
          emojiJsonRelease=$(gh api repos/muan/unicode-emoji-json/releases/latest -q .tag_name)
          echo "::set-output name=emojiJsonRelease::$emojiJsonRelease"
          if [[ $emojiJsonRelease == $(git describe) ]]
          then
            cd ../twemoji
            twemojiRelease=$(gh api repos/twitter/twemoji/releases/latest -q .tag_name)
            echo "::set-output name=twemojiRelease::$emojiJsonRelease"
            if [[ $twemojiRelease == $(git describe) ]]
            then
              echo "::set-output name=status::up-to-date"
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      emojiJsonRelease: ${{ steps.release-check.outputs.emojiJsonRelease }}
      twemojiRelease: ${{ steps.release-check.outputs.twemojiRelease }}
      status: ${{ steps.release-check.outputs.status }}

  generate:
    runs-on: ubuntu-latest
    needs:
      - check
    if: "needs.check.outputs.status != 'up-to-date'"
    name: Generate Emoticon Set and Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Update submodules
        run: |
          git -C unicode-emoji-json checkout ${{ needs.check.outputs.emojiJsonRelease }}
          git -C twemoji checkout ${{ needs.check.outputs.twemojiRelease }}
      - name: Generate
        run: |
          python3 definition-generator.py
          tar -czvf generated twemoji-for-jabber.tar.gz
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update to latest dependencies
      - name: Punlish release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            *.tar.gz
