---
on:
  schedule:
    - cron: '39 2 * * *'
  push:
    branches:
      - main
    paths:
      - base_version
      - metadata.json
  workflow_dispatch:
    inputs:
      skip_checks:
        description: |
          Skip all checks and updates; Generate and publish directly
        required: false
        default: false
        type: boolean

name: Generate Emojis
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check for Updates
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Check for new releases
        id: release-check
        run: |
          cd twemoji
          twemojiRelease=$(gh api repos/twitter/twemoji/releases/latest -q .tag_name)
          echo "::set-output name=twemojiRelease::$twemojiRelease"
          cd ..
          if [[ $twemojiRelease == $(git -C twemoji describe) ]]
          then
            echo "::set-output name=twemojiStatus::up-to-date"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      twemojiRelease: ${{ steps.release-check.outputs.twemojiRelease }}
      twemojiStatus: ${{ steps.release-check.outputs.twemojiStatus }}

  generate:
    runs-on: ubuntu-latest
    needs:
      - check
    if: "inputs.skip_checks || github.event_name == 'push' || needs.check.outputs.twemojiStatus != 'up-to-date'"
    name: Generate Twemoji Set and Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Update twemoji submodule
        run: |
          if [[ $twemojiRelease != $(git -C twemoji describe) ]]
          then
            git -C twemoji fetch --tags
            git -C twemoji checkout ${{ needs.check.outputs.twemojiRelease }}
          fi
      - name: Generate Twemoji set
        id: generate
        run: |
          python3 generator.py
          base_version=$(cat base_version)
          echo "::set-output name=version::${base_version}-twe-${{ needs.check.outputs.twemojiRelease }}-emojidata-$(git log --format=%h metadata.json)"
          echo "::set-output name=base_version::$base_version"
          cd generated
          tar -czf ../twemoji-for-jabber.tar.gz *
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update twemoji version
      - name: Publish release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.generate.outputs.version }}
          title: Version ${{ steps.generate.outputs.base_version }} (Twemoji ${{ needs.check.outputs.twemojiRelease }})
          files: |
            *.tar.gz
